#+TITLE: setenv-file
#+OPTIONS: toc:nil

* setenv-file                                 :readme:commentary:info:ignore:

  Set or unset environment variables from an "env" file.

  This package provides two interactive functions:

  1. =setenv-file-set=: set all the env vars in an env file
  2. =setenv-file-unset=: unset all the env vars in an env file

  When used interactively, each function prompts for a file. By default, the
  prompt begins at =setenv-file-dir=.

* Installation                                                       :readme:

  Copy =setenv-file.el= to your machine, and load it:

  #+begin_src emacs-lisp
    (load "/path/to/setenv-file.el")
  #+end_src

  Or, using straight:

  #+begin_src emacs-lisp
    (straight-use-package
     '(setenv-file :type git
                   :host github
                   :repo "cfclrk/setenv-file"))
  #+end_src

* Usage                                              :readme:commentary:info:

  Start by creating an env file in =setenv-file-dir= (by default, =~/.env/=).
  For example, create this file in =~/.env/foo=:

  #+begin_src sh
    FOO=~/foo
    BAR=$FOO/bar
    ОФИС=ДОМ
    BAZ=nosubst:FOO$BAR
  #+end_src

  Note that you can customize =setenv-file-dir= if you like, like this:

  #+begin_src emacs-lisp
    (setq setenv-file-dir
          (expand-file-name "~/another/path/"))
  #+end_src

** Interactive

  Now, set environment variables in Emacs using =M-x setenv-file=, and navigate
  to an env file.

  View your new environment variables with =M-x getenv=.

  Unset all of the variables defined in an env file.

** In elisp

   To set env variables defined in =~/.env/foo=:

   #+begin_src emacs-lisp
     (setenv-file "foo" setenv-file-dir)
   #+end_src

** In org-mode

   The example below shows a convenient way to declare and set environment
   variables in an =org= document:

   #+begin_example
   #+NAME: env
   | Var  | Value           |
   |------+-----------------|
   | FOO  | ~/foo           |
   | BAR  | $FOO/bar        |
   | ОФИС | ДОМ             |
   | BAZ  | nosubst:FOO$BAR |

   #+begin_src emacs-lisp :var env=env
     (setenv-file-export-pairs env)
   #+end_src
   #+end_example

* File Format                                        :readme:commentary:info:

  Each line in the file should be in a =KEY=VALUE= format, with one entry per
  line. This package does not invoke a shell to interpret the file, so most
  shell-isms will not work. However, the env file may:

  - Use existing environment variables
  - Define an environment variable and use it in successive lines
  - A =~= is expanded if it is the first character in the value

* Development                                                        :readme:

  1. =make dep=: Install dependencies
  2. =make test=: Run unit tests (you must run =make dep= first!)
  3. =make doc=: Runs an org export on =doc/doc.org= which creates:

     * =README.md=
     * The =;;; Commentary= section in =setenv-file.el=
     * Package texinfo (=.texi= and =.info=) in =doc/=

* See Also                                                           :readme:

  - [[https://github.com/wbolster/emacs-direnv][emacs-direnv]]
  - [[https://github.com/purcell/envrc][envrc]]
  - [[https://github.com/articuluxe/parsenv][parsenv]]

* Notes                                                            :noexport:

  TODO: Maybe this isn't the way to do it. Another possibility is to use the
  =sh= shell to evaluate the file, and then diff the result against the current
  environment. I /think/ that is what =direnv= does.

  TODO: Make setenv-file-set and setenv-file-unset functions. Can they just be
  aliases?

  - Test to ensure multibyte strings are normalized
  - Test value surrounded quotes
  - Test value with special chars like quotes and commas
  - Check with melpazoid (https://github.com/riscy/melpazoid)
  - Set up a [[https://github.com/marketplace/actions/emacs-lisp-check][GitHub Action]]
  - Add package-lint to tests
