\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename /Users/chris.clark/Projects/setenv-file/doc/setenv-file.info
@settitle setenv-file
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@finalout
@titlepage
@title setenv-file
@author Chris Clark
@end titlepage

@ifnottex
@node Top
@top setenv-file
@end ifnottex

@menu
* setenv-file::
* How To::
* File Format::
* Development::
* See Also::
@end menu

@node setenv-file
@chapter setenv-file

Set or unset environment variables from a file.

This package provides an interactive function @samp{setenv-file} to set environment
variables defined in a file. With one @samp{C-u} prefix argument, @samp{setenv-file}
unsets the environment variables defined in the file.

When used interactively, @samp{setenv-file} prompts for a file, defaulting to the
directory @samp{setenv-file-dir}.

@node How To
@chapter How To

Create a file with environment variable definitions. For example:

@example
FOO=~/foo
BAR=$FOO/bar
ОФИС=ДОМ
@end example

Set those environment variables in Emacs using @samp{M-x setenv-file}, and navigate
to the file. View your new environment variables with @samp{M-x getenv}.

To customize the default directory where you keep your env files:

@lisp
(setq setenv-file-dir (expand-file-name "~/.env/"))
@end lisp

@node File Format
@chapter File Format

Each line in the file should be in a @samp{KEY=VALUE} format, with one entry per
line. This package does not invoke a shell to interpret the file, so most
shell-isms will not work. However, the env file may:

@itemize
@item
Use existing environment variables
@item
Define and environment variable and use it in successive lines
@item
Tildes are expanded if they are the first character of the value
@end itemize

@node Development
@chapter Development

@enumerate
@item
Install dependencies: @samp{make install}
@item
Run tests: @samp{make test}
@item
Generate documentation: @samp{make docs}
@end enumerate

@node See Also
@chapter See Also

@itemize
@item
@uref{https://github.com/articuluxe/parsenv, parsenv}
@item
@uref{https://github.com/wbolster/emacs-direnv, emacs-direnv}
@item
@uref{https://github.com/christianromney/projectile-direnv, projectile-direnv}
@end itemize

@bye